---

- name: Find Local UCS File Name
  ansible.builtin.find:
    paths: "{{ backup_path }}"
    patterns: "*.ucs"
  register: ucs_fetch
  delegate_to: localhost

- name: Pause for 30 seconds
  ansible.builtin.pause:
    seconds: 30

- name: Compare IP Address with original node
  ansible.builtin.set_fact:
    temp_hostname: "{{ hostvars[item].inventory_hostname }}"
  loop: "{{ groups['ha_pair_source'] }}"
  when: hostvars[item].ansible_host == ansible_host

- name: Run Restore Command with Platform-Migrate
  ansible.builtin.command: "tmsh load /sys ucs {{ item.path | basename }} no-license platform-migrate"
  register: restore_task
  changed_when: restore_task.rc != 0
  loop: "{{ ucs_fetch.files }}"
  when:
    - item.path is defined
    - temp_hostname in item.path

- name: Debug Output of Restore
  ansible.builtin.debug:
    var: restore_task
