---

- name: Set AOM Username/Pwd -Override
  f5networks.f5_modules.bigip_command:
    commands: >
      run /util bash -c "
      expect -c 'spawn aom_setup_user -o;
      sleep 1;
      send -- {{ ansible_user }}\r;
      sleep 1;
      send -- {{ ansible_password }}\r;
      sleep 1;'"
    provider: "{{ provider }}"

- name: SAVE RUNNING CONFIG ON BIG-IP
  f5networks.f5_modules.bigip_config:
    provider: "{{ provider }}"
    save: true
