# F5 Source Details
server_port: 443

# Imperative Provider
provider:
  server: "{{ ansible_host }}"
  user: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  server_port: "{{ server_port }}"
  no_f5_teem: true
  validate_certs: false

# Declarative Provider Variables
ansible_httpapi_password: "{{ ansible_password }}"
ansible_network_os: f5networks.f5_bigip.bigip
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: "{{ server_port }}"
ansible_command_timeout: 600
ansible_httpapi_use_proxy: false
