# F5 Destination Details
server_port: 443

# Each variable here is overridable but have defaults defined to prevent an undefined situation (Default 4 Core, 14848MB Ram, 120GB Storage, on Slot 1 )
cpu_cores: "{{ override_cpu | default(4) | int }}"
disk_size: "{{ override_disk_size | default(120) | int }}"
memory: "{{ override_memory | default(((3.5 * 1024 * (cpu_cores | int)) + 512) | int) | int }}"
tenant_nodes: "{{ [override_node | default(1) | int] }}"
cryptos: "{{ override_cryptos | default('enabled') }}"

# F5 Destination MGMT-IP and VLAN Details
mgmt_ip: 192.170.14.85
mgmt_sn_cidr: 24
mgmt_gw: 192.170.14.1
# This is currently
mgmt_vlan: 3014

# Imperative Provider
provider:
  server: "{{ ansible_host }}"
  user: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  server_port: "{{ server_port }}"
  no_f5_teem: true
  validate_certs: false

# Declarative Provider Variables
ansible_httpapi_password: "{{ ansible_password }}"
ansible_network_os: "f5networks.f5os.f5os"
ansible_httpapi_use_ssl: true
ansible_httpapi_use_proxy: false
ansible_httpapi_validate_certs: false
ansible_httpapi_port: "{{ server_port }}"
ansible_command_timeout: 1800
persistent_log_messages: tenant_info.true
vlan_list: []
