---

- name: "[01] Bastion Backup-Cleanup"
  hosts: backup-host
  roles:
    - clean_up
    - create_backup_path

- name: "[02] Backup Source BIG-IP Crypto Files"
  hosts: f5_source
  connection: local
  gather_facts: false
  roles:
    - backup_crypto_keys
    - backup_info_variables

- name: "[03] Backup Source BIG-IP UCS File"
  hosts: f5_source
  connection: httpapi
  gather_facts: false
  roles:
    - backup_ucs_file

- name: "[04] Copy Source BIG-IP Crypto-UCS Files to Bastion"
  hosts: backup-host
  roles:
    - copy_files_to_backup_host

- name: "[05] Disable Source F5 (BIGSTART STOP)"
  hosts: f5_source
  connection: local
  gather_facts: false
  roles:
    - disable_f5_tmm

- name: "[06] Build and Start Destination F5"
  hosts: f5_destination_partition
  connection: httpapi
  gather_facts: false
  roles:
    - create_f5_os_tenant
    - start_f5_os_tenant

- name: "[07] Setup and Restore Destination BIG-IP Crypto Files"
  hosts: f5_destination_tenant
  connection: local
  gather_facts: false
  roles:
    - set_admin_password_shell
    - restore_crypto_keys

- name: "[08] Copy Source BIG-IP UCS File to Destination BIG-IP"
  hosts: f5_destination_tenant
  connection: httpapi
  gather_facts: false
  roles:
    - copy_ucs_file

- name: "[09] Restore Destination BIG-IP UCS"
  hosts: f5_destination_tenant
  connection: ssh
  gather_facts: false
  roles:
    - restore_ucs

- name: "[10] Wait for UCS Restore to Complete"
  hosts: f5_destination_tenant
  connection: httpapi
  gather_facts: false
  roles:
    - restore_ucs_wait
