---

- name: Store Variable for Hostname from Group
  ansible.builtin.set_fact:
    temp_hostname: "{{ hostvars[item].inventory_hostname }}"
  loop: "{{ groups['ha_pair_source'] }}"
  when: hostvars[item].ansible_host == ansible_host

- name: Load backup inventory JSON
  ansible.builtin.set_fact:
    temp_inventory: "{{ lookup('file', backup_path + '/inventory_' + temp_hostname + '.json') | from_json }}"
  delegate_to: localhost

- name: Collect BIG-IP information
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - traffic-groups
    provider: "{{ provider }}"
  delegate_to: localhost
  register: traffic_group

- name: Debug
  ansible.builtin.debug:
    var: temp_inventory

- name: Debug
  ansible.builtin.debug:
    var: traffic_group

- name: Trigger HA Failover
  f5networks.f5_modules.bigip_command:
    commands:
      - "run cm failover {{ item.name }} standby"
    provider: "{{ provider }}"
  loop: "{{ traffic_group.traffic_groups }}"
  when:
    - item.is_floating is defined
    - item.is_floating | lower == 'yes'

# - name: Wait until host is unreachable (port 22 closed)
#   ansible.builtin.wait_for:
#     host: "{{ ansible_host }}"
#     port: 22
#     state: started  # Wait for port to be open (but we want it to fail)
#     timeout: 5
#     connect_timeout: 2
#   register: port_up_check
#   ignore_errors: true
#   delegate_to: localhost
#   until: port_up_check.failed
#   retries: 30
#   delay: 10

# - name: Confirm host is now offline
#   ansible.builtin.debug:
#     msg: "Host {{ ansible_host }} is now unreachable (port 22 closed)"
