---

- name: "[01] Bastion Backup-Cleanup"
  hosts: backup-host
  roles:
    - clean_up
    - create_backup_path

- name: "[02] Backup Source (Standby/Active) BIG-IP Crypto Files"
  hosts: ha_pair_source
  connection: local
  gather_facts: false
  roles:
    - backup_crypto_keys
    - backup_info_variables
    - remove_as3

- name: "[03] Backup Source BIG-IP UCS File (Standby/Active) - Phase 1 - Standby"
  hosts: ha_pair_source
  connection: httpapi
  gather_facts: false
  roles:
    - backup_ucs_file

- name: "[04] Copy Source (Standby/Active) BIG-IP Crypto-UCS Files to Bastion - Phase 1 - Standby"
  hosts: backup-host
  roles:
    - copy_files_to_backup_host
